// The single source of truth for the course skeleton.
// generate.mjs turns this into folders + README files.

export const years = [
  {
    n: 1,
    folder: 'Year1.Foundations-Frontend',
    title: 'Software & Frontend Foundations',
    transformation: '"I know how to code."',
    goal: 'Understand how computers and the web really work, then build accessible, well-typed, tested frontend applications with JavaScript, TypeScript and React.',
    weights: { Knowledge: 25, Coding: 30, Projects: 30, Architecture: 15 },
  },
  {
    n: 2,
    folder: 'Year2.Backend-FullStack',
    title: 'Backend & Full-Stack Engineering',
    transformation: '"I can build complete applications."',
    goal: 'Go deep on Node.js, databases, APIs, authentication, testing, Next.js and security, and ship a real SaaS application end to end.',
    weights: { Knowledge: 25, Coding: 30, Projects: 30, Architecture: 15 },
  },
  {
    n: 3,
    folder: 'Year3.Production-Architecture',
    title: 'Production, Cloud, DevOps, Architecture & AI',
    transformation: '"I understand how production systems are engineered."',
    goal: 'Run, deploy, observe, scale and design systems: Linux, Docker, CI/CD, cloud, Terraform, observability, architecture, system design, distributed systems and AI engineering.',
    weights: { Knowledge: 15, Coding: 25, Projects: 30, Architecture: 30 },
  },
];

export const months = [
  // ───────────────────────────── YEAR 1 ─────────────────────────────
  {
    n: 1, year: 1, slug: 'ComputingFundamentals', title: 'Computing Fundamentals',
    bigIdea: 'A computer is a very fast, very obedient kitchen. The CPU is the chef, RAM is the kitchen counter, storage is the pantry, and a program is the recipe. This month you learn how the kitchen works, how to talk to it through the terminal, and how to write recipes that are fast (algorithms) and well organised (data structures).',
    outcomes: [
      'Explain what happens inside a computer when a program runs (CPU, RAM, storage, OS, processes, threads).',
      'Convert numbers between decimal, binary and hexadecimal, and explain how text and decimals are stored.',
      'Explain the difference between a compiler, an interpreter and a runtime like Node.js.',
      'Use the terminal confidently and write small JavaScript programs with Node.js.',
      'Describe Big-O and pick a sensible data structure (array, linked list, stack, queue, hash map, tree, graph) for a problem.',
      'Build a CLI application with no framework: the Student Record Management System.',
    ],
    topics: {
      'Hardware & OS': ['CPU', 'RAM', 'Storage', 'Operating systems', 'Processes', 'Threads', 'Filesystems'],
      'Data': ['Binary', 'Hexadecimal', 'Data representation (integers, text, floats)'],
      'Running code': ['Compilers', 'Interpreters', 'Runtime environments', 'Terminal', 'Command line (Windows + Linux)'],
      'Computer science': ['Algorithms', 'Big-O', 'Arrays', 'Linked lists', 'Stacks', 'Queues', 'Hash maps', 'Trees', 'Graphs', 'Recursion'],
    },
    weeks: [
      {
        folder: 'W1.HowComputersRunPrograms', title: 'How Computers Run Programs',
        focus: ['Software engineering', 'CPU, RAM, storage', 'Binary & hex', 'OS, processes, threads, files', 'Compilers, interpreters, runtimes'],
        days: ['D1 What Is Software Engineering?', 'D2 CPU, RAM & Storage', 'D3 Binary, Hex & Data Representation', 'D4 Operating Systems, Processes, Threads & Files', 'D5 Compilers, Interpreters & Runtimes', 'D6 Project: System Inspector CLI', 'D7 Review & Weekly Quiz'],
      },
      {
        folder: 'W2.TerminalAndJavaScriptSurvivalKit', title: 'Terminal & JavaScript Survival Kit',
        focus: ['Terminal navigation', 'Files & folders from the CLI', 'JS values, conditions, loops', 'Functions, arrays, objects', 'Reading input & modules'],
        days: ['D1 The Terminal: Your Remote Control', 'D2 Files, Folders & Pipes (PowerShell + Bash)', 'D3 JavaScript Values, Conditions & Loops', 'D4 Functions, Arrays & Objects', 'D5 Modules, Input & Writing a Real CLI', 'D6 Project: Todo CLI with a JSON file', 'D7 Review & Weekly Quiz'],
      },
      {
        folder: 'W3.AlgorithmsAndComplexity', title: 'Algorithms & Complexity',
        focus: ['What an algorithm is', 'Big-O', 'Searching', 'Sorting', 'Recursion'],
        days: ['D1 What Is an Algorithm?', 'D2 Big-O: Counting Steps, Not Seconds', 'D3 Searching: Linear vs Binary', 'D4 Sorting: Bubble, Insertion, Merge', 'D5 Recursion', 'D6 Project: Benchmark Lab', 'D7 Review & Weekly Quiz'],
      },
      {
        folder: 'W4.DataStructuresAndProject', title: 'Data Structures & Month Project',
        focus: ['Arrays vs linked lists', 'Stacks & queues', 'Hash maps', 'Trees & graphs', 'Student Record Management System'],
        days: ['D1 Arrays vs Linked Lists', 'D2 Stacks & Queues', 'D3 Hash Maps', 'D4 Trees & Graphs', 'D5 Choosing the Right Structure', 'D6 Project: Student Record Management System', 'D7 Month 1 Exam'],
      },
    ],
    project: {
      name: 'Student Record Management System (CLI)',
      brief: 'A command-line program with no framework that stores students, courses and grades in a JSON file. The point is logic and data structures, not pretty screens.',
      features: ['Add / edit / delete / list students', 'Record grades per course and compute averages', 'Search by name (hash map) and sort by grade (your own sort)', 'Undo the last action (stack)', 'Save and load from a JSON file', 'Automated tests for the core logic'],
    },
    layers: [
      'How do I use the terminal, Node and basic data structures?',
      'What is the CPU/OS/runtime actually doing when my code runs?',
      'Which data structure fits this problem, and what does it cost in time and memory?',
    ],
  },
  {
    n: 2, year: 1, slug: 'HowTheInternetAndWebWork', title: 'How the Internet & Web Work',
    bigIdea: 'The internet is a giant postal system. Every computer has an address (IP), every program has a door number (port), DNS is the phone book, and HTTP is the language letters are written in. This month you follow one letter from your keyboard to a server and back.',
    outcomes: [
      'Explain step by step what happens between typing example.com and seeing the page.',
      'Describe IP, ports, TCP, UDP, DNS, HTTP and HTTPS/TLS and how they stack together.',
      'Read and write raw HTTP requests and responses, including methods, headers and status codes.',
      'Explain cookies, sessions and caching and why each exists.',
      'Describe reverse proxies and CDNs and draw where they sit.',
    ],
    topics: {
      'Networking': ['Internet', 'IP addresses', 'TCP/IP', 'Ports', 'DNS'],
      'HTTP': ['HTTP & HTTPS', 'TLS', 'Request/response lifecycle', 'Methods', 'Headers', 'Status codes'],
      'State & speed': ['Cookies', 'Sessions', 'Caching'],
      'Architecture': ['Browser rendering', 'Client/server', 'Reverse proxies', 'CDNs'],
    },
    weeks: [
      { title: 'Networks: The Postal System', focus: ['IP addresses', 'Ports', 'TCP vs UDP', 'The TCP/IP model', 'DNS'] },
      { title: 'HTTP: The Language of the Web', focus: ['Request/response', 'Methods', 'Status codes', 'Headers', 'curl & DevTools Network tab'] },
      { title: 'Security & Memory of the Web', focus: ['HTTPS & TLS handshake', 'Cookies', 'Sessions', 'Caching headers'] },
      { title: 'From Server to Pixels + Project', focus: ['Browser rendering pipeline', 'Client/server architecture', 'Reverse proxies', 'CDNs', 'HTTP client project'] },
    ],
    project: {
      name: 'Hand-made HTTP Client & Network Inspector',
      brief: 'Build an HTTP client in JavaScript twice: once with a raw TCP socket (node:net) writing the HTTP text yourself, once with fetch. Inspect real requests and write the essay "What happens when I type example.com?".',
      features: ['Raw GET over TCP (you write the request line and headers)', 'Parse status line, headers and body yourself', 'Same request with fetch, compare results', 'DNS lookup with node:dns', 'Written explanation with a diagram'],
    },
    layers: ['How do I make and inspect HTTP requests?', 'How do packets, DNS, TCP and TLS actually move my data?', 'Where should caching, proxies and CDNs sit in a real architecture?'],
  },
  {
    n: 3, year: 1, slug: 'HTMLMastery', title: 'HTML Mastery',
    bigIdea: 'HTML is the skeleton of a web page. It says what each thing IS (a heading, a button, a form), not what it looks like. A good skeleton helps browsers, search engines and screen readers understand your page.',
    outcomes: [
      'Write valid, semantic HTML documents from memory.',
      'Build accessible forms with native validation.',
      'Use tables, images and multimedia correctly.',
      'Add metadata for SEO and social sharing.',
      'Explain why semantic HTML is the foundation of accessibility.',
    ],
    topics: {
      'Structure': ['Document structure', 'Semantic HTML', 'Metadata', 'SEO'],
      'Content': ['Text', 'Links', 'Images', 'Multimedia', 'Tables'],
      'Interaction': ['Forms', 'Form validation'],
      'Access': ['Accessibility foundations'],
    },
    weeks: [
      { title: 'Document Structure & Semantics', focus: ['How browsers parse HTML', 'head vs body', 'Semantic landmarks', 'Headings & text', 'Links & navigation'] },
      { title: 'Media & Data', focus: ['Images & responsive images', 'Audio & video', 'Tables done right', 'Figures & captions'] },
      { title: 'Forms', focus: ['Inputs & labels', 'Native validation', 'Fieldsets & grouping', 'How forms submit (GET vs POST)'] },
      { title: 'Metadata, SEO, Accessibility + Project', focus: ['Meta tags & Open Graph', 'SEO basics', 'Accessibility foundations', 'Multipage site'] },
    ],
    project: {
      name: 'Multipage Website (no frameworks)',
      brief: 'A complete multipage website in pure HTML: Home, About, Products, Contact, Blog and Registration.',
      features: ['6 pages sharing a consistent semantic layout', 'Accessible registration and contact forms with validation', 'Products table and blog articles', 'Proper metadata on every page', 'Passes the W3C validator with zero errors'],
    },
    layers: ['How do I write the right element?', 'How does the browser turn HTML into a DOM and an accessibility tree?', 'When is plain HTML enough, and when do I need more?'],
  },
  {
    n: 4, year: 1, slug: 'CSSMastery', title: 'CSS Mastery',
    bigIdea: 'If HTML is the skeleton, CSS is the clothes and the furniture arrangement. The browser follows a strict rulebook (the cascade) to decide which clothes win. Learn the rulebook and CSS stops feeling random.',
    outcomes: [
      'Predict which CSS rule wins using the cascade, specificity and inheritance.',
      'Build any layout with Flexbox and Grid.',
      'Make responsive designs with media and container queries.',
      'Use custom properties, transitions and animations.',
      'Compare CSS architectures (BEM, utility-first, CSS Modules, Tailwind) and choose one.',
    ],
    topics: {
      'Rules': ['Cascade', 'Specificity', 'Inheritance', 'Box model', 'Units', 'Colors', 'Typography'],
      'Layout': ['Positioning', 'Flexbox', 'CSS Grid'],
      'Adaptive': ['Responsive CSS', 'Media queries', 'Container queries', 'Custom properties'],
      'Motion': ['Transitions', 'Animations'],
      'Architecture': ['BEM', 'Utility CSS', 'Component CSS', 'CSS Modules', 'Tailwind concepts'],
    },
    weeks: [
      { title: 'The Rulebook', focus: ['Cascade & specificity', 'Inheritance', 'Box model', 'Units & colors', 'Typography'] },
      { title: 'Layout', focus: ['Normal flow & positioning', 'Flexbox', 'Grid', 'Layout recipes'] },
      { title: 'Responsive & Alive', focus: ['Mobile-first media queries', 'Container queries', 'Custom properties', 'Transitions & animations'] },
      { title: 'CSS Architecture + Project', focus: ['BEM', 'Utility-first & Tailwind ideas', 'CSS Modules', 'SaaS landing page'] },
    ],
    project: {
      name: 'Professional SaaS Landing Page (from scratch)',
      brief: 'Recreate a professional SaaS landing page with no component libraries: hero, features, pricing, testimonials, FAQ and footer.',
      features: ['Fully responsive from 320px to 1920px', 'Grid + Flexbox layout', 'Design tokens as custom properties', 'Dark mode', 'Respects prefers-reduced-motion'],
    },
    layers: ['How do I style and lay out a page?', 'How does the browser compute styles, layout and paint?', 'Which CSS architecture fits this team and project size?'],
  },
  {
    n: 5, year: 1, slug: 'JavaScriptCore', title: 'JavaScript Core',
    bigIdea: 'JavaScript is the brain you add to the web page. This month you learn to think in JavaScript without leaning on AI: small daily katas until the basics are automatic.',
    outcomes: [
      'Write JavaScript fluently: types, operators, conditions, loops, functions.',
      'Use arrays, objects and strings with their core methods.',
      'Explain scope and closures with your own examples.',
      'Use higher-order functions (map, filter, reduce) naturally.',
      'Split code into ES modules.',
    ],
    topics: {
      'Basics': ['Variables', 'Types', 'Operators', 'Conditions', 'Loops'],
      'Functions': ['Functions', 'Scope', 'Closures', 'Higher-order functions'],
      'Data': ['Arrays', 'Array methods', 'Objects', 'Strings'],
      'Organisation': ['Modules'],
    },
    weeks: [
      { title: 'Values & Control Flow', focus: ['let/const', 'Types & coercion', 'Operators', 'Conditions', 'Loops'] },
      { title: 'Functions & Scope', focus: ['Function forms', 'Parameters & defaults', 'Scope', 'Closures'] },
      { title: 'Arrays, Objects, Strings', focus: ['Array methods', 'Objects & destructuring', 'Spread/rest', 'String methods'] },
      { title: 'Higher-Order Functions, Modules + Project', focus: ['map/filter/reduce', 'Composing functions', 'ES modules', 'Finance tracker'] },
    ],
    project: {
      name: 'Personal Finance Tracker',
      brief: 'A browser app for income and expenses, with no framework.',
      features: ['Add income and expenses', 'Categories', 'Filtering', 'Totals and balance', 'Persists with localStorage', 'Core logic in tested modules'],
    },
    layers: ['How do I write JavaScript?', 'How does JS scope and memory work?', 'When should logic be pure functions vs stateful objects?'],
  },
  {
    n: 6, year: 1, slug: 'AdvancedJavaScript', title: 'Advanced JavaScript',
    bigIdea: 'JavaScript has one chef (one thread) who never waits around. The event loop is the chef\'s to-do list. Once you understand that list, promises, async/await and the DOM stop being magic.',
    outcomes: [
      'Explain execution context, the call stack and hoisting.',
      'Explain prototypes, classes and the four rules of "this".',
      'Explain the event loop, macrotasks and microtasks, and predict output order.',
      'Write robust async code with promises, async/await and error handling.',
      'Build interactive interfaces with the DOM and events.',
    ],
    topics: {
      'Engine': ['Execution context', 'Call stack', 'Hoisting', 'Closures'],
      'Objects': ['Prototypes', 'this', 'Classes', 'OOP', 'Functional programming'],
      'Async': ['Event loop', 'Microtasks', 'Promises', 'Async/await', 'Error handling'],
      'Browser': ['Browser APIs', 'DOM', 'Events'],
    },
    weeks: [
      { title: 'Inside the Engine', focus: ['Execution context', 'Call stack', 'Hoisting', 'Closures in depth', 'this'] },
      { title: 'Objects: Prototypes, Classes, Paradigms', focus: ['Prototype chain', 'Classes', 'OOP', 'Functional programming'] },
      { title: 'Asynchronous JavaScript', focus: ['Event loop', 'Microtasks', 'Promises', 'async/await', 'Error handling'] },
      { title: 'DOM, Events + Project', focus: ['DOM tree', 'Events & delegation', 'Browser APIs', 'Project board'] },
    ],
    project: {
      name: 'Interactive Project Management Board (Trello-style)',
      brief: 'Boards, lists and cards with drag and drop, in vanilla JavaScript.',
      features: ['Create boards, lists and cards', 'Drag & drop between lists', 'Event delegation', 'Persisted state', 'Simulated async save with loading and error states'],
    },
    layers: ['How do I use promises, classes and the DOM?', 'How do the engine and event loop execute my code?', 'When is OOP better than FP (and vice versa) for a feature?'],
  },
  {
    n: 7, year: 1, slug: 'GitGitHubAndDeveloperWorkflow', title: 'Git, GitHub & Professional Developer Workflow',
    bigIdea: 'Git is a time machine plus a parallel universe machine for your code. GitHub is where teams meet to review each other\'s universes before joining them together.',
    outcomes: [
      'Explain how Git stores history (commits, trees, blobs, branches as pointers).',
      'Branch, merge, rebase and resolve conflicts calmly.',
      'Undo safely with reset, revert and stash.',
      'Run a professional pull-request workflow with reviews, issues and releases.',
      'Set up npm/pnpm, ESLint, Prettier and debugging for a project.',
    ],
    topics: {
      'Git': ['init', 'add', 'commit', 'branch', 'merge', 'rebase', 'reset', 'revert', 'stash', 'tags'],
      'GitHub': ['Repositories', 'Pull requests', 'Code reviews', 'Issues', 'Projects', 'Releases'],
      'Tooling': ['VS Code', 'npm', 'pnpm', 'package.json', 'ESLint', 'Prettier', 'Debugging', 'DevTools'],
    },
    weeks: [
      { title: 'How Git Thinks', focus: ['Objects & the commit graph', 'init/add/commit', 'log & diff', 'Good commit messages'] },
      { title: 'Branches & Time Travel', focus: ['branch & merge', 'rebase', 'Conflicts', 'reset/revert/stash', 'tags'] },
      { title: 'GitHub Team Workflow', focus: ['Pull requests', 'Code review', 'Issues & Projects', 'Releases'] },
      { title: 'Professional Tooling + Team Simulation', focus: ['npm/pnpm & semver', 'ESLint & Prettier', 'Debugging', 'Team simulation'] },
    ],
    project: {
      name: 'Solo Team Simulation',
      brief: 'Run the Finance Tracker as if you were a team: issues, feature branches, pull requests, self-review with a checklist, releases and a changelog.',
      features: ['At least 8 issues and 8 PRs', 'One deliberate merge conflict resolved', 'ESLint + Prettier enforced', 'Tagged releases with notes'],
    },
    layers: ['How do I use Git commands?', 'How does Git store and move history?', 'Which branching strategy fits this team?'],
  },
  {
    n: 8, year: 1, slug: 'AccessibilityAndResponsiveEngineering', title: 'Accessibility & Responsive Engineering',
    bigIdea: 'A good building has ramps, not just stairs. Accessibility means everyone can use your app: keyboard users, screen-reader users, people on tiny phones or slow connections.',
    outcomes: [
      'Apply WCAG principles (POUR) to real interfaces.',
      'Make everything keyboard-usable with correct focus management.',
      'Use ARIA only when HTML is not enough, and use it correctly.',
      'Build mobile-first fluid layouts with responsive typography and images.',
      'Audit a site with screen readers and automated tools.',
    ],
    topics: {
      'Accessibility': ['WCAG', 'Keyboard navigation', 'Screen readers', 'Focus management', 'ARIA', 'Accessible forms', 'Semantic HTML'],
      'Responsive': ['Mobile first', 'Fluid layouts', 'Responsive typography', 'Images', 'Breakpoints', 'Adaptive interfaces'],
    },
    weeks: [
      { title: 'WCAG & Keyboard', focus: ['Why accessibility matters', 'POUR principles', 'Keyboard navigation', 'Focus order'] },
      { title: 'Screen Readers & ARIA', focus: ['Accessibility tree', 'Screen reader testing', 'ARIA roles/states', 'Accessible forms & errors'] },
      { title: 'Responsive Engineering', focus: ['Mobile first', 'Fluid layouts', 'clamp() typography', 'Responsive images'] },
      { title: 'Auditing + Project', focus: ['axe & Lighthouse', 'Manual audits', 'Education portal'] },
    ],
    project: {
      name: 'Accessibility-First Education Portal',
      brief: 'A government or education portal where accessibility is the first requirement, not an afterthought.',
      features: ['Fully keyboard operable', 'Screen-reader tested', 'Accessible multi-step form with errors', 'Responsive 320px to desktop', 'Written audit report'],
    },
    layers: ['How do I make components accessible?', 'How do assistive technologies read my page?', 'How do I bake accessibility into a team\'s process?'],
  },
  {
    n: 9, year: 1, slug: 'APIsAndAsynchronousJavaScript', title: 'APIs & Asynchronous JavaScript',
    bigIdea: 'An API is a restaurant menu for software. You order in a known format (a request) and the kitchen sends back your dish (a response). This month you learn to order well, wait politely and handle the kitchen being slow or wrong.',
    outcomes: [
      'Consume REST APIs with fetch and async/await.',
      'Handle pagination, authentication headers, API keys and rate limits.',
      'Build resilient clients with retries, backoff, timeouts and AbortController.',
      'Show loading, empty and error states properly.',
      'Explain REST vs GraphQL vs WebSockets vs webhooks.',
    ],
    topics: {
      'REST': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'JSON', 'Fetch API'],
      'Real-world concerns': ['Pagination', 'Authentication headers', 'API keys', 'Rate limits', 'Retries', 'AbortController', 'Error handling'],
      'Other styles': ['GraphQL', 'WebSockets', 'Webhooks'],
    },
    weeks: [
      { title: 'REST & fetch', focus: ['REST ideas', 'Methods revisited', 'JSON', 'fetch + async/await'] },
      { title: 'Real APIs', focus: ['Pagination', 'Auth headers & API keys', 'Rate limits', 'Keeping secrets out of the browser'] },
      { title: 'Resilience', focus: ['Timeouts & AbortController', 'Retries with backoff', 'Error handling', 'UI states'] },
      { title: 'Beyond REST + Project', focus: ['GraphQL', 'WebSockets', 'Webhooks', 'Dashboard'] },
    ],
    project: {
      name: 'Global Information Dashboard',
      brief: 'A dashboard combining several public APIs (weather, countries, currency, news, etc.).',
      features: ['At least 4 APIs', 'Loading/empty/error states everywhere', 'Retry + cancel', 'Pagination or infinite scroll', 'Client-side caching'],
    },
    layers: ['How do I call an API?', 'What happens on the network and in the event loop during a request?', 'Which API style fits which problem?'],
  },
  {
    n: 10, year: 1, slug: 'UIUXEngineering', title: 'UI/UX Engineering',
    bigIdea: 'Good design is like a good signpost: people know where to go without thinking. You learn to design before you code, so code is solving the right problem.',
    outcomes: [
      'Apply typography, color, spacing and hierarchy deliberately.',
      'Map user journeys and flows, then wireframe them.',
      'Build a small design system with tokens and components.',
      'Design empty, error and loading states on purpose.',
      'Prototype in Figma before writing code.',
    ],
    topics: {
      'Visual': ['Typography', 'Color theory', 'Layout', 'Visual hierarchy', 'Spacing'],
      'Experience': ['User journeys', 'User flows', 'Wireframes', 'Prototypes', 'Cognitive load'],
      'Systems': ['Design systems', 'Empty states', 'Error states', 'Loading states', 'Figma'],
    },
    weeks: [
      { title: 'Visual Foundations', focus: ['Typography', 'Color', 'Spacing scales', 'Hierarchy'] },
      { title: 'Designing Experiences', focus: ['User journeys', 'Flows', 'Wireframes', 'Cognitive load'] },
      { title: 'Design Systems', focus: ['Tokens', 'Components & variants', 'State design'] },
      { title: 'Figma + Project', focus: ['Figma fundamentals', 'Prototyping', 'Design handoff'] },
    ],
    project: {
      name: 'Design-First Application',
      brief: 'Design an application before coding it: wireframes, design system, prototype, final interface.',
      features: ['User journey map', 'Wireframes', 'Design tokens + components', 'Clickable prototype', 'Coded final interface matching the design'],
    },
    layers: ['How do I make interfaces look right?', 'Why do users perceive layouts the way they do?', 'When is a design system worth its cost?'],
  },
  {
    n: 11, year: 1, slug: 'TypeScript', title: 'TypeScript',
    bigIdea: 'TypeScript is spell-check for your program\'s shapes. It catches "you promised a number but gave a string" before your users ever see it.',
    outcomes: [
      'Type objects, functions and modules with interfaces and aliases.',
      'Use unions, narrowing, type guards and discriminated unions to model states.',
      'Write reusable generic functions and types.',
      'Use utility, conditional and mapped types.',
      'Migrate a JavaScript project to strict TypeScript.',
    ],
    topics: {
      'Basics': ['Primitive types', 'Objects', 'Interfaces', 'Type aliases', 'tsconfig'],
      'Modelling': ['Union types', 'Narrowing', 'Type guards', 'Discriminated unions'],
      'Reuse': ['Generics', 'Utility types'],
      'Advanced': ['Conditional types', 'Mapped types'],
    },
    weeks: [
      { title: 'Types Basics', focus: ['Why TypeScript', 'Primitives & objects', 'Interfaces vs aliases', 'tsconfig & strict'] },
      { title: 'Modelling with Types', focus: ['Unions', 'Narrowing', 'Type guards', 'Discriminated unions'] },
      { title: 'Generics & Utilities', focus: ['Generic functions', 'Generic constraints', 'Utility types'] },
      { title: 'Type-Level Programming + Project', focus: ['Conditional types', 'Mapped types', 'Migration strategy'] },
    ],
    project: {
      name: 'TypeScript Rewrite',
      brief: 'Rewrite one previous JavaScript application (Finance Tracker or Project Board) entirely in strict TypeScript.',
      features: ['strict: true with zero any', 'Discriminated unions for UI state', 'Typed API layer', 'Migration notes explaining bugs the types caught'],
    },
    layers: ['How do I type my code?', 'How does the compiler check and erase types?', 'How much typing is worth it for this codebase?'],
  },
  {
    n: 12, year: 1, slug: 'ReactFundamentals', title: 'React Fundamentals',
    bigIdea: 'React lets you build a UI from LEGO bricks (components). You describe what the screen should look like for the current data, and React works out what to change.',
    outcomes: [
      'Build UIs from components, props and state.',
      'Handle events, forms, lists and conditional rendering.',
      'Use hooks (useState, useEffect and friends) correctly.',
      'Compose components and add routing.',
      'Deliver the Year 1 capstone with tests, accessibility and API integration.',
    ],
    topics: {
      'Core': ['JSX', 'Components', 'Props', 'State', 'Events'],
      'Patterns': ['Forms', 'Hooks', 'Lists', 'Conditional rendering', 'Component composition'],
      'Apps': ['Routing', 'Testing basics'],
    },
    weeks: [
      { title: 'Components & JSX', focus: ['JSX', 'Components', 'Props', 'Lists & keys', 'Conditional rendering'] },
      { title: 'State & Hooks', focus: ['useState', 'Events', 'Forms', 'useEffect'] },
      { title: 'Composition & Routing', focus: ['Lifting state', 'Composition', 'Routing'] },
      { title: 'Year 1 Capstone', focus: ['Planning', 'Build', 'Test', 'Present'] },
    ],
    project: {
      name: 'YEAR 1 CAPSTONE: Learning Management System Frontend',
      brief: 'A substantial React + TypeScript frontend for a learning platform.',
      features: ['Authentication UI', 'Dashboard', 'Courses', 'Progress tracking', 'Notifications', 'Responsive + accessible', 'Tests', 'API integration (mock or real)'],
    },
    layers: ['How do I build React components?', 'How does React rendering work?', 'Is React appropriate for this architecture?'],
  },

  // ───────────────────────────── YEAR 2 ─────────────────────────────
  {
    n: 13, year: 2, slug: 'AdvancedReact', title: 'Advanced React',
    bigIdea: 'Now you look under React\'s hood: when it re-draws, why, and how to stop wasted work. You also learn where different kinds of data should live.',
    outcomes: [
      'Explain rendering and reconciliation and fix unnecessary re-renders.',
      'Write custom hooks and use context and reducers well.',
      'Use error boundaries, Suspense and lazy loading.',
      'Profile and fix React performance problems.',
      'Choose between local state, Zustand, Redux Toolkit and TanStack Query.',
    ],
    topics: {
      'Rendering': ['Rendering', 'Reconciliation', 'Memoization', 'useMemo', 'useCallback'],
      'Patterns': ['Custom hooks', 'Context', 'Reducers', 'Error boundaries', 'Suspense', 'Lazy loading'],
      'Performance': ['Performance profiling'],
      'State management': ['Zustand', 'Redux Toolkit', 'TanStack Query'],
    },
    weeks: [
      { title: 'Rendering Deep Dive', focus: ['Render & commit', 'Reconciliation & keys', 'Memoization', 'Profiler'] },
      { title: 'Reusable Logic', focus: ['Custom hooks', 'Context', 'useReducer'] },
      { title: 'Resilient UIs', focus: ['Error boundaries', 'Suspense', 'Lazy loading & code splitting'] },
      { title: 'State Management + Project', focus: ['Client vs server state', 'Zustand', 'Redux Toolkit', 'TanStack Query'] },
    ],
    project: { name: 'LMS Frontend Refactor', brief: 'Refactor the Year 1 capstone: profile it, fix re-renders, move server data to TanStack Query and add error boundaries.', features: ['Before/after profiler evidence', 'Custom hooks library', 'Server state via TanStack Query', 'Error boundaries + Suspense'] },
    layers: ['How do I use hooks and state libraries?', 'How does React decide what to re-render?', 'Which state belongs where in a large app?'],
  },
  {
    n: 14, year: 2, slug: 'NodeJS', title: 'Node.js',
    bigIdea: 'Node.js is JavaScript let out of the browser and given the keys to the computer: files, network and processes. Learn Node itself before any framework hides it.',
    outcomes: [
      'Explain the Node runtime: V8, libuv and the event loop phases.',
      'Work with the filesystem, buffers and streams.',
      'Use events, EventEmitter, child processes and worker threads.',
      'Manage configuration with environment variables.',
      'Build an HTTP server with the raw http module.',
    ],
    topics: {
      'Runtime': ['Node runtime', 'Modules (ESM/CJS)', 'Event loop', 'Processes', 'Environment variables'],
      'I/O': ['FS', 'Buffers', 'Streams'],
      'Concurrency': ['Events', 'EventEmitter', 'Worker threads', 'Child processes'],
    },
    weeks: [
      { title: 'The Runtime', focus: ['V8 + libuv', 'Modules', 'process & env', 'Event loop phases'] },
      { title: 'Files, Buffers, Streams', focus: ['fs promises', 'Buffers', 'Readable/Writable/Transform', 'Backpressure'] },
      { title: 'Events & Concurrency', focus: ['EventEmitter', 'Worker threads', 'Child processes'] },
      { title: 'Raw HTTP + Project', focus: ['http module', 'Routing by hand', 'Body parsing', 'CLI + server project'] },
    ],
    project: { name: 'Node CLI + HTTP Server Without Express', brief: 'A log-analysis CLI using streams, plus a small JSON API built with only node:http.', features: ['Streams large files without loading them into memory', 'Hand-written router', 'JSON body parsing & error handling', 'Graceful shutdown'] },
    layers: ['How do I use Node APIs?', 'How does libuv schedule I/O?', 'When is Node the wrong tool (CPU-heavy work)?'],
  },
  {
    n: 15, year: 2, slug: 'DatabaseFundamentals', title: 'Database Fundamentals',
    bigIdea: 'A database is a super-organised library. Tables are shelves, rows are books, keys are catalogue numbers, and SQL is how you ask the librarian for exactly what you need.',
    outcomes: [
      'Model data with tables, keys, relationships and constraints.',
      'Normalise a schema and draw ER diagrams.',
      'Write SQL: CRUD, JOINs, GROUP BY, subqueries, CTEs and window functions.',
      'Explain transactions and ACID.',
    ],
    topics: {
      'Theory': ['Tables', 'Rows', 'Relationships', 'Primary keys', 'Foreign keys', 'Constraints', 'Transactions', 'Normalization'],
      'SQL': ['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'JOIN', 'GROUP BY', 'CTE', 'Subqueries', 'Window functions'],
    },
    weeks: [
      { title: 'The Relational Model', focus: ['Tables & keys', 'Relationships', 'Constraints'] },
      { title: 'Designing Schemas', focus: ['Normalization', 'ER diagrams', 'When to denormalise'] },
      { title: 'SQL Core', focus: ['CRUD', 'JOINs', 'GROUP BY & aggregates'] },
      { title: 'SQL Advanced + Transactions', focus: ['Subqueries', 'CTEs', 'Window functions', 'ACID transactions'] },
    ],
    project: { name: 'Library System Database', brief: 'Design and query a library database: books, members, loans and fines.', features: ['ER diagram', 'Normalised schema with constraints', '30 SQL challenge queries', 'Transaction-safe loan workflow'] },
    layers: ['How do I write SQL?', 'How does a database store and find rows?', 'When is relational the right model?'],
  },
  {
    n: 16, year: 2, slug: 'PostgreSQL', title: 'PostgreSQL',
    bigIdea: 'PostgreSQL is a professional-grade library with a genius librarian (the query planner). You learn how the librarian thinks so your questions are answered in milliseconds, not minutes.',
    outcomes: [
      'Explain PostgreSQL architecture and MVCC.',
      'Create the right indexes and read EXPLAIN ANALYZE plans.',
      'Choose isolation levels and understand locks.',
      'Use JSONB and full-text search.',
      'Design a production-quality schema for a large domain.',
    ],
    topics: {
      'Internals': ['PostgreSQL architecture', 'MVCC', 'Query planner', 'EXPLAIN'],
      'Performance': ['Indexes', 'Performance tuning'],
      'Concurrency': ['Transactions', 'Isolation', 'Locks'],
      'Features': ['JSONB', 'Full-text search'],
    },
    weeks: [
      { title: 'Architecture & Types', focus: ['Processes & memory', 'psql', 'Data types', 'JSONB'] },
      { title: 'Indexes & Plans', focus: ['B-tree/GIN/GiST', 'EXPLAIN ANALYZE', 'Query planner'] },
      { title: 'Concurrency', focus: ['MVCC', 'Isolation levels', 'Locks & deadlocks'] },
      { title: 'Search, Tuning + Project', focus: ['Full-text search', 'Performance tuning', 'University DB'] },
    ],
    project: { name: 'University Management System Database', brief: 'Design the database for a university: students, staff, departments, courses, enrolments, timetables and grades.', features: ['Full ER diagram', 'Seed data at realistic scale (100k+ rows)', 'Indexed queries with EXPLAIN evidence', 'Concurrency-safe enrolment'] },
    layers: ['How do I use PostgreSQL?', 'How do the planner, indexes and MVCC work?', 'When do I need read replicas, partitioning or another database?'],
  },
  {
    n: 17, year: 2, slug: 'BackendEngineeringAndExpress', title: 'Backend Engineering & Express',
    bigIdea: 'A backend is a well-run restaurant kitchen: the waiter (route) takes the order, the head chef (controller) delegates, cooks (services) do the work, and the storeroom keeper (repository) fetches ingredients. Everyone has one job.',
    outcomes: [
      'Design clean REST APIs.',
      'Structure a backend in layers: routes, controllers, services, repositories.',
      'Write middleware for validation, errors, logging and config.',
      'Explain dependency injection and why it helps testing.',
    ],
    topics: {
      'API': ['REST APIs', 'Routes', 'Controllers'],
      'Architecture': ['Services', 'Repositories', 'Dependency injection concepts'],
      'Cross-cutting': ['Middleware', 'Validation', 'Error handling', 'Logging', 'Configuration'],
    },
    weeks: [
      { title: 'REST Design & Express Basics', focus: ['Resource design', 'Routes', 'Controllers'] },
      { title: 'Layered Backend', focus: ['Services', 'Repositories', 'Dependency injection'] },
      { title: 'Cross-Cutting Concerns', focus: ['Middleware', 'Validation (zod)', 'Error handling', 'Logging', 'Config'] },
      { title: 'Project Build', focus: ['Complete REST API', 'Docs (OpenAPI)', 'Review'] },
    ],
    project: { name: 'Complete REST API', brief: 'A layered REST API (e.g. for the University system) on PostgreSQL.', features: ['Layered structure', 'Validation on every input', 'Consistent error format', 'Structured logging', 'OpenAPI specification'] },
    layers: ['How do I build an Express API?', 'How do requests flow through middleware?', 'How should a backend be layered for change?'],
  },
  {
    n: 18, year: 2, slug: 'AuthenticationAndAuthorization', title: 'Authentication & Authorization',
    bigIdea: 'Authentication asks "who are you?" (showing your ID card). Authorization asks "what are you allowed to do?" (which rooms your card opens). You build both yourself before letting a library hide them.',
    outcomes: [
      'Hash and verify passwords correctly.',
      'Implement sessions with secure cookies, and JWT with refresh tokens.',
      'Explain OAuth 2.0 and OpenID Connect flows.',
      'Implement RBAC and explain ABAC.',
      'Build email verification, account recovery and MFA.',
    ],
    topics: {
      'Authentication': ['Password hashing', 'Cookies', 'Sessions', 'JWT', 'Refresh tokens', 'MFA'],
      'Delegation': ['OAuth', 'OpenID Connect'],
      'Authorization': ['RBAC', 'ABAC'],
      'Account lifecycle': ['Email verification', 'Account recovery'],
    },
    weeks: [
      { title: 'Passwords & Sessions', focus: ['Hashing (argon2/bcrypt)', 'Cookies', 'Sessions'] },
      { title: 'Tokens', focus: ['JWT', 'Refresh tokens & rotation', 'Where to store tokens'] },
      { title: 'OAuth, OIDC, MFA', focus: ['OAuth 2.0 flows', 'OpenID Connect', 'TOTP MFA'] },
      { title: 'Authorization + Project', focus: ['RBAC', 'ABAC', 'Verification & recovery'] },
    ],
    project: { name: 'Your Own Authentication System', brief: 'Build auth from primitives: registration, login, sessions, refresh tokens, roles, email verification, password reset and MFA.', features: ['Secure password storage', 'Session + JWT variants', 'RBAC middleware', 'Email verification & reset', 'TOTP MFA', 'Threat notes'] },
    layers: ['How do I add login?', 'How do hashing, cookies and tokens actually protect users?', 'Build or buy (Auth0, Clerk, etc.) for this product?'],
  },
  {
    n: 19, year: 2, slug: 'PrismaAndDataAccess', title: 'Prisma & Data Access',
    bigIdea: 'An ORM is a translator between your code\'s objects and the database\'s tables. Great translators save time, but you must still know both languages to spot mistranslations.',
    outcomes: [
      'Model schemas, relations and migrations in Prisma.',
      'Write queries, transactions and raw SQL when needed.',
      'Detect and fix N+1 queries.',
      'Design a data-access layer with the repository pattern.',
    ],
    topics: {
      'Prisma': ['Schema', 'Models', 'Relationships', 'Queries', 'Transactions', 'Migrations', 'Seeds', 'Raw SQL'],
      'Performance': ['N+1 queries', 'Query optimization'],
      'Patterns': ['Repository pattern', 'Data-access layers'],
    },
    weeks: [
      { title: 'Schema & Migrations', focus: ['Models & relations', 'Migrations', 'Seeds'] },
      { title: 'Querying', focus: ['CRUD', 'Relations', 'Transactions', 'Raw SQL'] },
      { title: 'Performance', focus: ['N+1', 'Select/include', 'Query logging'] },
      { title: 'Data-Access Patterns + Project', focus: ['Repository pattern', 'Unit of work', 'Migration of the REST API'] },
    ],
    project: { name: 'Migrate the REST API to Prisma', brief: 'Move the Month 17 API to Prisma behind repositories without changing the HTTP contract.', features: ['Migrations & seeds', 'Repository layer', 'N+1 audit with before/after query counts', 'Raw SQL for one reporting query'] },
    layers: ['How do I use Prisma?', 'What SQL does the ORM generate?', 'When is an ORM the wrong choice?'],
  },
  {
    n: 20, year: 2, slug: 'TestingEngineering', title: 'Testing Engineering',
    bigIdea: 'Tests are safety nets under a trapeze. With good nets you can try bold moves (refactors, new features) without fear.',
    outcomes: [
      'Explain the testing pyramid and pick the right test type.',
      'Write unit tests with Vitest.',
      'Write integration and API tests against a real test database.',
      'Test React components the way users use them.',
      'Write reliable E2E tests with Playwright.',
    ],
    topics: {
      'Strategy': ['Testing pyramid', 'Test doubles', 'Coverage'],
      'Levels': ['Unit testing', 'Integration testing', 'API testing', 'E2E testing'],
      'Tools': ['Vitest/Jest', 'React Testing Library', 'Playwright'],
    },
    weeks: [
      { title: 'Unit Testing', focus: ['Testing pyramid', 'Vitest', 'Mocks & fakes', 'TDD'] },
      { title: 'Integration & API', focus: ['Test databases', 'Supertest', 'Fixtures'] },
      { title: 'Component Testing', focus: ['React Testing Library', 'User-centric queries', 'Mocking fetch'] },
      { title: 'E2E + Assignment', focus: ['Playwright', 'Flaky tests', 'CI-ready suites'] },
    ],
    project: { name: 'Serious Test Suite', brief: 'Take a previous project and give it a professional automated test suite.', features: ['Unit + integration + E2E', 'Runs in one command', 'Meaningful coverage report', 'Zero flaky tests over 10 runs'] },
    layers: ['How do I write tests?', 'How do test runners, mocks and browsers automate checks?', 'What should (and should not) be tested here?'],
  },
  {
    n: 21, year: 2, slug: 'NextJSFundamentals', title: 'Next.js Fundamentals',
    bigIdea: 'Next.js is React with a built-in server and a map of your whole site. Some of your components now run in the kitchen (server) and some at the table (browser).',
    outcomes: [
      'Build apps with the App Router, layouts and nested routes.',
      'Explain Server vs Client Components and choose correctly.',
      'Fetch data on the server and set metadata.',
      'Write route handlers and error/loading UI.',
    ],
    topics: {
      'Routing': ['App Router', 'Routing', 'Layouts'],
      'Components': ['Server Components', 'Client Components'],
      'Data': ['Data fetching', 'Metadata', 'Route handlers'],
      'Resilience': ['Error boundaries', 'Loading UI'],
    },
    weeks: [
      { title: 'App Router', focus: ['File-based routing', 'Layouts', 'Navigation'] },
      { title: 'Server vs Client', focus: ['Server Components', 'Client Components', 'The boundary'] },
      { title: 'Data & Metadata', focus: ['Server data fetching', 'Metadata & SEO'] },
      { title: 'Route Handlers & Errors + Mini Project', focus: ['Route handlers', 'error.tsx & loading.tsx', 'Mini app'] },
    ],
    project: { name: 'Next.js Blog Platform', brief: 'A multi-author blog with server-rendered pages and a small API.', features: ['Nested layouts', 'Server data fetching', 'Route handlers', 'SEO metadata', 'Error & loading UI'] },
    layers: ['How do I build pages in Next.js?', 'How does server rendering and RSC streaming work?', 'When is Next.js (vs SPA or plain server) the right choice?'],
  },
  {
    n: 22, year: 2, slug: 'AdvancedNextJS', title: 'Advanced Next.js',
    bigIdea: 'Now you learn Next.js\'s memory (caching) and its shortcuts (server actions, streaming). Used well, they make apps fast. Used badly, they show stale data.',
    outcomes: [
      'Mutate data with Server Actions.',
      'Control caching and revalidation deliberately.',
      'Stream UI with Suspense.',
      'Add authentication and middleware.',
      'Use parallel and intercepting routes.',
    ],
    topics: {
      'Mutations': ['Server Actions'],
      'Caching': ['Caching', 'Revalidation', 'Streaming', 'Suspense'],
      'Security': ['Authentication', 'Middleware', 'Server/client boundaries'],
      'Advanced routing': ['Parallel routes', 'Intercepting routes'],
    },
    weeks: [
      { title: 'Server Actions', focus: ['Forms & mutations', 'Validation', 'Optimistic UI'] },
      { title: 'Caching & Streaming', focus: ['Cache layers', 'Revalidation', 'Streaming + Suspense'] },
      { title: 'Auth & Middleware', focus: ['Auth in Next', 'Middleware', 'Protecting server code'] },
      { title: 'Advanced Routing + Project', focus: ['Parallel routes', 'Intercepting routes', 'Production app'] },
    ],
    project: { name: 'Production-Style Next.js Application', brief: 'A complete app (e.g. job board or booking system) with auth, database, mutations and caching.', features: ['Auth + roles', 'Server Actions', 'Deliberate caching strategy (documented)', 'Streaming dashboards', 'Deployed'] },
    layers: ['How do I use Server Actions and caching?', 'How do the Next.js cache layers work?', 'Which rendering strategy fits each page?'],
  },
  {
    n: 23, year: 2, slug: 'WebSecurity', title: 'Web Security',
    bigIdea: 'To defend a castle you must think like the attacker. You break your own practice apps in a safe lab, then fix every hole.',
    outcomes: [
      'Explain the OWASP Top 10 with examples.',
      'Find and fix XSS, CSRF, SQL injection, SSRF and command injection.',
      'Configure CORS, CSP and security headers correctly.',
      'Protect secrets, rate-limit endpoints and manage dependency risk.',
      'Write a threat model.',
    ],
    topics: {
      'Framework': ['OWASP Top 10', 'Threat modeling'],
      'Injection': ['XSS', 'SQL injection', 'Command injection', 'SSRF'],
      'Browser': ['CSRF', 'CORS', 'CSP', 'Security headers'],
      'Operations': ['Broken authorization', 'Rate limiting', 'Secrets', 'Dependency attacks'],
    },
    weeks: [
      { title: 'Thinking Like an Attacker', focus: ['OWASP Top 10', 'Threat modeling (STRIDE)', 'Safe lab setup'] },
      { title: 'Injection', focus: ['SQL injection', 'Command injection', 'XSS'] },
      { title: 'Browser Defences', focus: ['CSRF', 'SSRF', 'CORS', 'CSP & headers'] },
      { title: 'Authorization & Supply Chain + Lab', focus: ['Broken access control', 'Rate limiting', 'Secrets', 'Dependency attacks'] },
    ],
    project: { name: 'Attack & Fix Lab', brief: 'Attack your own deliberately vulnerable test app in a local lab, then fix each vulnerability with tests proving it stays fixed.', features: ['At least 8 vulnerability classes', 'Exploit write-up + fix + regression test for each', 'Threat model document', 'Security headers score A'] },
    layers: ['How do I apply security controls?', 'How do these attacks work at the protocol level?', 'Which risks matter most for this product?'],
  },
  {
    n: 24, year: 2, slug: 'FullStackCapstone', title: 'Full-Stack Capstone',
    bigIdea: 'Everything comes together. Stop thinking in pages and start thinking Domain → Application → Data → Infrastructure.',
    outcomes: [
      'Turn business requirements into a domain model and architecture.',
      'Build a full SaaS: auth, authorization, payments, email, file storage, caching.',
      'Test, log and deploy it.',
      'Document it so another engineer could take over.',
    ],
    topics: {
      'Product': ['Requirements', 'Domain modeling'],
      'Build': ['Frontend', 'Backend', 'PostgreSQL', 'Authentication', 'Authorization', 'File storage', 'Email', 'Payments', 'Caching', 'API'],
      'Quality': ['Testing', 'Logging', 'Deployment', 'Documentation'],
    },
    weeks: [
      { title: 'Requirements & Architecture', focus: ['Requirements', 'Domain model', 'Architecture & ERD'] },
      { title: 'Core Build', focus: ['Auth', 'Data model', 'Core API & UI'] },
      { title: 'Business Features', focus: ['Payments', 'Email', 'File storage', 'Caching'] },
      { title: 'Ship It', focus: ['Tests', 'Logging', 'Deployment', 'Docs & demo'] },
    ],
    project: { name: 'YEAR 2 CAPSTONE: Team Project Management SaaS', brief: 'A multi-tenant SaaS for teams to manage projects, with billing.', features: ['Organisations, members, roles', 'Projects, tasks, comments, attachments', 'Stripe payments (test mode)', 'Transactional email', 'Caching', 'Full test suite', 'Deployed with logging'] },
    layers: ['How do I build each feature?', 'How do all the parts interact at runtime?', 'Is the architecture right for the business?'],
  },

  // ───────────────────────────── YEAR 3 ─────────────────────────────
  {
    n: 25, year: 3, slug: 'Linux', title: 'Linux',
    bigIdea: 'Almost every server in the world runs Linux. It is the ground your applications stand on, so you learn to live there comfortably.',
    outcomes: [
      'Navigate the filesystem and manage permissions, users and groups.',
      'Manage processes, signals and systemd services.',
      'Read logs and troubleshoot networking.',
      'Use SSH securely and write shell scripts.',
      'Deploy an app to a Linux server behind nginx.',
    ],
    topics: {
      'System': ['Filesystem', 'Permissions', 'Users', 'Processes', 'Services', 'Logs'],
      'Network': ['SSH', 'Networking'],
      'Automation': ['Shell scripting'],
    },
    weeks: [
      { title: 'Filesystem & Permissions', focus: ['FHS', 'Permissions', 'Users & groups'] },
      { title: 'Processes & Services', focus: ['Processes & signals', 'systemd', 'journalctl & logs'] },
      { title: 'Networking & SSH', focus: ['ip/ss/dig/curl', 'SSH keys & config', 'Firewalls'] },
      { title: 'Scripting + Project', focus: ['Bash scripting', 'cron', 'Server deployment'] },
    ],
    project: { name: 'Run Your SaaS on a Linux Server', brief: 'Deploy the Year 2 capstone to a Linux VM by hand.', features: ['Hardened SSH', 'systemd service', 'nginx reverse proxy + TLS', 'Log rotation', 'Backup script'] },
    layers: ['How do I use Linux commands?', 'How do the kernel, processes and permissions work?', 'How should servers be configured and hardened?'],
  },
  {
    n: 26, year: 3, slug: 'Docker', title: 'Docker',
    bigIdea: 'A container is a lunchbox that holds your app plus everything it needs, so it works the same in every kitchen: your laptop, CI or the cloud.',
    outcomes: [
      'Explain containers vs virtual machines.',
      'Write efficient, secure Dockerfiles with multi-stage builds.',
      'Use volumes, networks and Compose for multi-service apps.',
      'Publish images to registries and scan them.',
    ],
    topics: {
      'Core': ['Containers', 'Images', 'Dockerfile', 'Multi-stage builds'],
      'Runtime': ['Volumes', 'Networks', 'Compose'],
      'Distribution': ['Registries', 'Container security'],
    },
    weeks: [
      { title: 'Containers & Images', focus: ['Namespaces & cgroups', 'Images & layers', 'docker run'] },
      { title: 'Dockerfiles', focus: ['Layer caching', 'Multi-stage', '.dockerignore', 'Non-root users'] },
      { title: 'Multi-Service Apps', focus: ['Volumes', 'Networks', 'Compose'] },
      { title: 'Registries & Security + Project', focus: ['Registries', 'Image scanning', 'Dockerize SaaS'] },
    ],
    project: { name: 'Dockerize the SaaS', brief: 'Containerise the Year 2 capstone with its database, cache and worker.', features: ['Small, non-root images', 'Compose for local dev', 'Health checks', 'Image scanned with zero critical CVEs'] },
    layers: ['How do I use Docker?', 'How do namespaces, cgroups and layers work?', 'When are containers overkill?'],
  },
  {
    n: 27, year: 3, slug: 'CICD', title: 'CI/CD',
    bigIdea: 'CI/CD is a factory conveyor belt: every change is automatically checked, packaged and delivered, so shipping becomes boring and safe.',
    outcomes: [
      'Build CI pipelines with GitHub Actions.',
      'Automate tests, linting and builds with caching.',
      'Deliver to environments with secrets managed safely.',
      'Release, deploy and roll back safely.',
    ],
    topics: {
      'CI': ['Continuous integration', 'GitHub Actions', 'Automated tests'],
      'CD': ['Continuous delivery', 'Deployment pipelines', 'Releases', 'Rollbacks'],
      'Safety': ['Secrets management', 'Environments & approvals'],
    },
    weeks: [
      { title: 'CI Basics', focus: ['Why CI', 'Workflows, jobs, steps', 'Triggers'] },
      { title: 'Quality Gates', focus: ['Tests & lint in CI', 'Matrices', 'Caching', 'Artifacts'] },
      { title: 'Delivery', focus: ['Environments', 'Secrets & OIDC', 'Releases & versioning'] },
      { title: 'Deployment Strategies + Project', focus: ['Blue/green & canary', 'Rollbacks', 'Pipeline project'] },
    ],
    project: { name: 'Your Own CI/CD Pipeline', brief: 'A full pipeline for the SaaS: PR checks, image build, staging deploy, manual approval, production deploy and one-click rollback.', features: ['Required PR checks', 'Docker image build + push', 'Staging + production environments', 'Documented rollback drill'] },
    layers: ['How do I write a workflow?', 'How do runners, caches and secrets work?', 'What deployment strategy fits the risk level?'],
  },
  {
    n: 28, year: 3, slug: 'CloudFundamentals', title: 'Cloud Fundamentals',
    bigIdea: 'The cloud is renting pieces of giant data centres by the minute. You learn the building blocks (compute, storage, network, identity) and how to stay secure and on budget.',
    outcomes: [
      'Explain regions, availability zones and the shared-responsibility model.',
      'Use IAM with least privilege.',
      'Choose between EC2, Lambda and containers for compute.',
      'Use S3, RDS, CloudFront, Route 53 and load balancers.',
      'Design a VPC and control cost.',
    ],
    topics: {
      'Foundations': ['Regions', 'Availability zones', 'IAM', 'Cost management'],
      'Compute': ['EC2', 'Lambda', 'Load balancers'],
      'Data': ['S3', 'RDS', 'CloudFront'],
      'Network': ['VPC', 'Route 53'],
    },
    weeks: [
      { title: 'Cloud Foundations & IAM', focus: ['Cloud models', 'Regions & AZs', 'IAM', 'Budgets & alerts'] },
      { title: 'Compute', focus: ['EC2', 'Lambda', 'Load balancers', 'Auto scaling'] },
      { title: 'Storage & Databases', focus: ['S3', 'RDS', 'CloudFront'] },
      { title: 'Networking + Project', focus: ['VPC design', 'Route 53', 'Deploy SaaS on AWS'] },
    ],
    project: { name: 'SaaS on AWS', brief: 'Deploy the SaaS on AWS with a proper network, managed database and CDN, with budget alarms on from day one.', features: ['Private subnets for data', 'RDS with backups', 'S3 + CloudFront for assets', 'Least-privilege IAM', 'Cost report'] },
    layers: ['How do I use AWS services?', 'How do cloud networks and IAM evaluate access?', 'Which managed services are worth their cost?'],
  },
  {
    n: 29, year: 3, slug: 'InfrastructureAsCode', title: 'Infrastructure as Code (Terraform)',
    bigIdea: 'Instead of clicking around a cloud console, you write a recipe for your infrastructure. Recipes can be reviewed, versioned and re-run exactly.',
    outcomes: [
      'Write Terraform with providers, resources, variables and outputs.',
      'Manage state safely with remote backends and locking.',
      'Build reusable modules.',
      'Run separate dev/staging/prod environments from code.',
    ],
    topics: {
      'Core': ['Providers', 'Resources', 'Variables', 'Outputs'],
      'State': ['State', 'Remote state', 'Locking'],
      'Scale': ['Modules', 'Infrastructure environments'],
    },
    weeks: [
      { title: 'Terraform Basics', focus: ['Why IaC', 'Providers & resources', 'plan/apply/destroy'] },
      { title: 'Variables, Outputs, State', focus: ['Variables', 'Outputs', 'How state works'] },
      { title: 'Modules & Remote State', focus: ['Modules', 'Remote backends', 'Locking'] },
      { title: 'Environments + Project', focus: ['Workspaces vs folders', 'Terraform in CI', 'Infra from code'] },
    ],
    project: { name: 'SaaS Infrastructure from Code', brief: 'Recreate the Month 28 AWS setup entirely with Terraform modules, with dev and prod environments.', features: ['Reusable modules', 'Remote state + locking', 'Plan on PR, apply on merge', 'Destroy/recreate drill'] },
    layers: ['How do I write Terraform?', 'How does Terraform diff desired vs real state?', 'How should infra code be split across teams?'],
  },
  {
    n: 30, year: 3, slug: 'Observability', title: 'Observability',
    bigIdea: 'Observability puts windows and gauges on your system, like a car dashboard. When something breaks you can see why instead of guessing.',
    outcomes: [
      'Emit structured logs with correlation IDs.',
      'Define and collect metrics; build dashboards.',
      'Trace requests across services with OpenTelemetry.',
      'Write actionable alerts, health checks and SLOs.',
    ],
    topics: {
      'Signals': ['Logs', 'Metrics', 'Traces'],
      'Operations': ['Alerts', 'Dashboards', 'Health checks', 'SLOs'],
      'Tools': ['OpenTelemetry', 'Application monitoring', 'Structured logging', 'Error tracking'],
    },
    weeks: [
      { title: 'Structured Logging', focus: ['Log levels & structure', 'Correlation IDs', 'Log aggregation'] },
      { title: 'Metrics & Dashboards', focus: ['RED & USE methods', 'Prometheus concepts', 'Grafana dashboards'] },
      { title: 'Tracing', focus: ['Spans & context propagation', 'OpenTelemetry'] },
      { title: 'Alerting & SLOs + Project', focus: ['Health checks', 'SLOs & error budgets', 'Actionable alerts', 'Error tracking'] },
    ],
    project: { name: 'Make the SaaS Observable', brief: 'Instrument the SaaS with logs, metrics, traces and alerts, then run an incident drill.', features: ['Dashboards for RED metrics', 'End-to-end traces', 'SLOs with alerts', 'Incident post-mortem write-up'] },
    layers: ['How do I add logs, metrics and traces?', 'How does telemetry flow from app to dashboard?', 'What is worth alerting on?'],
  },
  {
    n: 31, year: 3, slug: 'PerformanceAndScalability', title: 'Performance & Scalability',
    bigIdea: 'Performance is how fast one customer is served. Scalability is serving a million customers without the kitchen catching fire. You measure first, then fix the real bottleneck.',
    outcomes: [
      'Measure and improve Core Web Vitals and bundle size.',
      'Optimise databases with pooling, indexing and query tuning.',
      'Use Redis caching, rate limiting and background jobs.',
      'Scale horizontally with load balancing, replication and CDNs.',
      'Load-test and read the results.',
    ],
    topics: {
      'Frontend': ['Core Web Vitals', 'Bundle size', 'Images', 'Lazy loading', 'Caching'],
      'Backend': ['Connection pooling', 'Indexing', 'Query optimization', 'Redis', 'Rate limiting', 'Background jobs'],
      'System': ['Load balancing', 'Horizontal scaling', 'Replication', 'CDN', 'Stateless architecture'],
    },
    weeks: [
      { title: 'Frontend Performance', focus: ['Core Web Vitals', 'Bundles', 'Images', 'Lazy loading'] },
      { title: 'Backend Performance', focus: ['Pooling', 'Indexing', 'Query tuning', 'Redis caching'] },
      { title: 'Work Off the Hot Path', focus: ['Rate limiting', 'Background jobs', 'Queues'] },
      { title: 'Scaling Out + Load Testing', focus: ['Stateless services', 'Load balancing', 'Replication', 'k6 load tests'] },
    ],
    project: { name: 'Scale the SaaS 10x', brief: 'Load-test the SaaS, find bottlenecks, fix them and prove the improvement with numbers.', features: ['Baseline + final load test reports', 'Redis cache with invalidation plan', 'Background job queue', 'Horizontal scaling behind a load balancer'] },
    layers: ['How do I apply caching, pooling and queues?', 'Where does time actually go in a request?', 'Which scaling approach fits the traffic and budget?'],
  },
  {
    n: 32, year: 3, slug: 'SoftwareArchitecture', title: 'Software Architecture',
    bigIdea: 'Architecture is city planning for code: where the roads, districts and walls go so the city can grow for years without becoming a traffic jam. From now on you design first, then build.',
    outcomes: [
      'Apply SOLID, cohesion and coupling to real code.',
      'Compare layered, clean and hexagonal architecture.',
      'Decide between a modular monolith and microservices.',
      'Use DDD: bounded contexts, aggregates, ubiquitous language.',
      'Record decisions with ADRs and C4 diagrams.',
    ],
    topics: {
      'Principles': ['SOLID', 'Separation of concerns', 'Cohesion', 'Coupling'],
      'Styles': ['Layered architecture', 'Clean Architecture', 'Hexagonal architecture', 'Modular monoliths', 'Microservices'],
      'Domain': ['Domain-driven design'],
      'Communication': ['ADRs', 'C4 diagrams'],
    },
    weeks: [
      { title: 'Principles', focus: ['SOLID', 'Cohesion & coupling', 'Separation of concerns'] },
      { title: 'Architectural Styles', focus: ['Layered', 'Clean', 'Hexagonal'] },
      { title: 'Monolith vs Services', focus: ['Modular monolith', 'Microservices trade-offs', 'Module boundaries'] },
      { title: 'DDD & Communicating Design', focus: ['Bounded contexts', 'Aggregates', 'ADRs', 'C4'] },
    ],
    project: { name: 'Architecture Design Exercise', brief: 'Instead of "build a feature": design the architecture for a given business problem, then refactor the SaaS toward a modular monolith.', features: ['Context map', 'C4 diagrams (levels 1-3)', '5+ ADRs', 'Enforced module boundaries in code'] },
    layers: ['How do I apply these patterns?', 'How do dependencies flow in each style?', 'Which architecture fits this team, domain and stage?'],
  },
  {
    n: 33, year: 3, slug: 'SystemDesign', title: 'System Design',
    bigIdea: 'System design is drawing the blueprint for a huge building before anyone lays a brick: how many people will use it, where the lifts go, what happens in a fire.',
    outcomes: [
      'Use a repeatable framework: requirements, estimation, API, data, high-level and deep dive.',
      'Estimate capacity (QPS, storage, bandwidth).',
      'Combine caches, queues, load balancers, storage and CDNs.',
      'Design well-known systems and discuss failure modes.',
    ],
    topics: {
      'Method': ['Requirements', 'Capacity estimation', 'APIs', 'Data modeling'],
      'Building blocks': ['Databases', 'Caches', 'Queues', 'Load balancers', 'Storage', 'CDNs'],
      'Case studies': ['URL shortener', 'Chat application', 'YouTube', 'Uber', 'Netflix', 'E-commerce', 'Learning platform', 'Payment system'],
      'Reliability': ['Failure modes'],
    },
    weeks: [
      { title: 'The Framework', focus: ['Requirements', 'Back-of-envelope estimation', 'API & data model'] },
      { title: 'Building Blocks', focus: ['Caches', 'Queues', 'Load balancers', 'Storage & CDNs'] },
      { title: 'Case Studies I', focus: ['URL shortener', 'Chat', 'E-commerce', 'Payments'] },
      { title: 'Case Studies II + Mock Interviews', focus: ['YouTube/Netflix', 'Uber', 'Learning platform', 'Mock interviews'] },
    ],
    project: { name: 'System Design Portfolio', brief: 'Eight written system designs with diagrams, estimates and trade-offs, plus recorded mock interviews.', features: ['One design doc per system', 'Capacity estimates', 'Failure-mode analysis', 'Recorded mock interviews'] },
    layers: ['What components exist?', 'How do they behave under load and failure?', 'Which design is right for these requirements?'],
  },
  {
    n: 34, year: 3, slug: 'DistributedSystems', title: 'Distributed Systems',
    bigIdea: 'A distributed system is a team of computers passing notes. Notes get lost, arrive twice or arrive late, and computers disagree. You learn why tools like Kafka exist, not just their APIs.',
    outcomes: [
      'Explain CAP/PACELC and consistency models.',
      'Explain replication, partitioning and consensus at an intuitive level.',
      'Design idempotent operations and sagas instead of distributed transactions.',
      'Build event-driven flows with queues (BullMQ, RabbitMQ, Kafka).',
    ],
    topics: {
      'Theory': ['CAP theorem', 'Consistency', 'Availability', 'Eventual consistency'],
      'Data': ['Replication', 'Partitioning', 'Consensus'],
      'Correctness': ['Distributed transactions', 'Sagas', 'Idempotency', 'Outbox pattern'],
      'Messaging': ['Message queues', 'Event-driven systems', 'Kafka', 'RabbitMQ', 'BullMQ'],
    },
    weeks: [
      { title: 'Theory', focus: ['Failure is normal', 'CAP & PACELC', 'Consistency models'] },
      { title: 'Replication & Partitioning', focus: ['Leader/follower', 'Partitioning', 'Consensus intuition (Raft)'] },
      { title: 'Correctness', focus: ['Idempotency', 'Sagas', 'Outbox', 'Exactly-once myths'] },
      { title: 'Messaging + Project', focus: ['Queues vs logs', 'BullMQ', 'RabbitMQ', 'Kafka'] },
    ],
    project: { name: 'Event-Driven Order System', brief: 'An order/payment/inventory flow across services using events, idempotency and a saga.', features: ['Idempotent consumers', 'Saga with compensation', 'Outbox pattern', 'Chaos test: kill a service mid-flow'] },
    layers: ['How do I use a message queue?', 'How do replication and delivery guarantees work?', 'Do I even need to distribute this?'],
  },
  {
    n: 35, year: 3, slug: 'AIEngineering', title: 'AI Engineering',
    bigIdea: 'A large language model is an extremely well-read autocomplete. AI engineering is building reliable products around it: giving it the right context, tools and guardrails, and measuring whether it actually works.',
    outcomes: [
      'Explain LLMs, transformers, tokens and embeddings.',
      'Use structured output, tool calling and streaming.',
      'Build RAG with a vector database and reranking.',
      'Build agents with memory and guardrails.',
      'Evaluate and observe AI features in production.',
    ],
    topics: {
      'Foundations': ['LLMs', 'Transformers', 'Tokens', 'Embeddings'],
      'Building': ['Prompt engineering', 'Structured output', 'Tool calling', 'Streaming'],
      'Retrieval': ['Vector databases', 'RAG', 'Reranking'],
      'Systems': ['Agents', 'Memory', 'Evaluation', 'Guardrails', 'AI observability'],
    },
    weeks: [
      { title: 'How LLMs Work', focus: ['Transformers intuition', 'Tokens & context windows', 'Embeddings'] },
      { title: 'Building with LLM APIs', focus: ['Prompting', 'Structured output', 'Tool calling', 'Streaming'] },
      { title: 'Retrieval', focus: ['Vector databases', 'RAG pipeline', 'Reranking'] },
      { title: 'Agents & Production + Project', focus: ['Agents & memory', 'Evals', 'Guardrails', 'AI observability'] },
    ],
    project: { name: 'AI Feature in a Real App', brief: 'Add an AI assistant to the SaaS or LMS: RAG over its data, tool calling into its API, with evals and guardrails.', features: ['RAG with citations', 'Tool calling with permission checks', 'Eval suite with a scored dataset', 'Cost and latency dashboard'] },
    layers: ['How do I call an LLM API?', 'How do tokens, embeddings and retrieval work?', 'When is AI the right solution, and how do I know it works?'],
  },
  {
    n: 36, year: 3, slug: 'EnterpriseCapstone', title: 'Enterprise Capstone',
    bigIdea: 'Your graduation project: a system close to what you want to engineer professionally, designed, built, secured, deployed, observed and documented like a real company would.',
    outcomes: [
      'Deliver an enterprise-grade system end to end.',
      'Produce complete architecture documentation.',
      'Operate it: CI/CD, cloud infrastructure, monitoring, disaster recovery.',
      'Present and defend your engineering decisions.',
    ],
    topics: {
      'System': ['Web application', 'API gateway', 'Application services', 'Database', 'Redis', 'Job queue', 'Object storage', 'AI services', 'Vector database'],
      'Delivery': ['GitHub', 'CI/CD', 'Docker', 'Cloud infrastructure', 'Monitoring'],
      'Documentation': ['Architecture docs', 'C4, ER and sequence diagrams', 'API specification', 'Security & threat model', 'Testing strategy', 'Observability plan', 'Database, caching, scaling & disaster-recovery strategies', 'Cost considerations'],
    },
    weeks: [
      { title: 'Requirements & Design', focus: ['Requirements', 'C4 & ADRs', 'Threat model'] },
      { title: 'Core Build', focus: ['Services', 'Data', 'API gateway'] },
      { title: 'AI, Jobs, Infrastructure', focus: ['AI services & vector DB', 'Job queue', 'Terraform & CI/CD'] },
      { title: 'Operate, Document, Present', focus: ['Monitoring', 'DR drill', 'Docs', 'Final presentation'] },
    ],
    project: { name: 'FINAL CAPSTONE: Enterprise Learning Platform', brief: 'Web app → API gateway → application services → PostgreSQL + Redis + job queue → object storage → AI services + vector DB, delivered via GitHub → CI/CD → Docker → cloud → monitoring.', features: ['All architecture deliverables', 'Deployed and monitored', 'Disaster-recovery drill performed', 'Cost report', 'Recorded presentation'] },
    layers: ['Can I build every part?', 'Do I understand how every part behaves in production?', 'Can I justify every decision and its trade-offs?'],
  },
];
